/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2020-05-29 15:58:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.E_DirecteurEtudes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/E.DirecteurEtudes/MenuDirecteurEtudes.jsp", Long.valueOf(1590686558232L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("  \t<title>Profile</title>\r\n");
      out.write("  \t\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/all.min.css\" type=\"text/css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/style.css\" type=\"text/css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/dataTables.bootstrap.css\" type=\"text/css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery.dataTables.min.css\" type=\"text/css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/fontawesome.min.css\" type=\"text/css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/bootstap.min.css\" type=\"text/css\" >\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-ui.min.css\" type=\"text/css\" >\r\n");
      out.write("\t\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\t\tbackground-color:#fff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t/***************** Modal confirm **********************/\r\n");
      out.write("\t.modal-confirm {\t\t\r\n");
      out.write("\t\tcolor: #636363;\r\n");
      out.write("\t\twidth: 325px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-confirm .modal-content {\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-confirm .modal-header {\r\n");
      out.write("\t\tborder-bottom: none;   \r\n");
      out.write("        position: relative;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-confirm h4 {\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tfont-size: 26px;\r\n");
      out.write("\t\tmargin: 30px 0 -15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-confirm .form-control, .modal-confirm .btn {\r\n");
      out.write("\t\tmin-height: 40px;\r\n");
      out.write("\t\tborder-radius: 3px; \r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-confirm .close {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("\t\ttop: -5px;\r\n");
      out.write("\t\tright: -5px;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t.modal-confirm .modal-footer {\r\n");
      out.write("\t\tborder: none;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tborder-radius: 5px;\r\n");
      out.write("\t\tfont-size: 13px;\r\n");
      out.write("\t}\t\r\n");
      out.write("\t.modal-confirm .icon-box {\r\n");
      out.write("\t\tcolor: #fff;\t\t\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\tleft: 0;\r\n");
      out.write("\t\tright: 0;\r\n");
      out.write("\t\ttop: -70px;\r\n");
      out.write("\t\twidth: 95px;\r\n");
      out.write("\t\theight: 95px;\r\n");
      out.write("\t\tborder-radius: 50%;\r\n");
      out.write("\t\tz-index: 9;\r\n");
      out.write("\t\t/* background: #82ce34; */\r\n");
      out.write("\t\tpadding: 15px;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tbox-shadow: 0px 2px 2px rgba(0, 0, 0, 0.1);\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-confirm .icon-box i {\r\n");
      out.write("\t\tfont-size: 58px;\r\n");
      out.write("\t\tposition: relative;\r\n");
      out.write("\t\ttop: 3px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.modal-confirm.modal-dialog {\r\n");
      out.write("\t\tmargin-top: 80px;\r\n");
      out.write("\t}\r\n");
      out.write("    .modal-confirm .btn {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\ttransition: all 0.4s;\r\n");
      out.write("        line-height: normal;\r\n");
      out.write("        border: none;\r\n");
      out.write("        width:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("/********************************************************************/\r\n");
      out.write("\t\t.page-header h3{\r\n");
      out.write("\t\tpadding:10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel-primary{\r\n");
      out.write("\t\tborder:1px solid #3071a9 !important;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel-body{\r\n");
      out.write("\t\t\tpadding:20px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel.with-nav-tabs .panel-heading{\r\n");
      out.write("\t\t    padding: 5px 5px 0 5px;\r\n");
      out.write("\t\t    background-color: #3071a9;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel.with-nav-tabs.panel-body{\r\n");
      out.write("\t\t    padding: 10px 15px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel.with-nav-tabs .nav-tabs{\r\n");
      out.write("\t\t\tborder-bottom: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel.with-nav-tabs .nav-justified{\r\n");
      out.write("\t\t\tmargin-bottom: -1px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*** PANEL PRIMARY ***/\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > a,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > a:focus {\r\n");
      out.write("\t\t    color: #fff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > .open > a,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > .open > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > .open > a:focus,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs >  a:focus {\r\n");
      out.write("\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\tbackground-color: #3071a9;\r\n");
      out.write("\t\t\tborder-color: transparent;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > a.active,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > a.active > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > a.active > a:focus {\r\n");
      out.write("\t\t\tcolor: #428bca;\r\n");
      out.write("\t\t\tbackground-color: #fff;\r\n");
      out.write("\t\t\tborder-color: #428bca;\r\n");
      out.write("\t\t\tborder-bottom-color: transparent;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu {\r\n");
      out.write("\t\t    background-color: #428bca;\r\n");
      out.write("\t\t    border-color: #3071a9;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > li > a {\r\n");
      out.write("\t\t    color: #fff;   \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > li > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > li > a:focus {\r\n");
      out.write("\t\t    background-color: #3071a9;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > .active > a,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > .active > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > .active > a:focus {\r\n");
      out.write("\t\t    background-color: #4a9fe9;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/********************************************************************/\r\n");
      out.write("\t\t\tinput.error {\r\n");
      out.write("\t\t    border-color: #f00 !important;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsmall.required {\r\n");
      out.write("\t\t\t    color:#f00;\r\n");
      out.write("\t\t\t}\r\n");
      out.write(".modal-backdrop {\r\n");
      out.write("   /* display: none; */\r\n");
      out.write("}\r\n");
      out.write("\t/**************** Data Table *******************/\r\n");
      out.write("\t\r\n");
      out.write("\t\t</style>\t\r\n");
      out.write("  </head>\r\n");
      out.write(" <body>\r\n");
      out.write("\t<div class=\"wrapper d-flex align-items-stretch\">\r\n");
      out.write("\t\t<nav id=\"sidebar\" class=\"active\">\r\n");
      out.write("\t\t\t<h1><a href=\"index.html\" class=\"logo\"><span class=\"fa fa-cubes\"></span></a></h1>\r\n");
      out.write("\t      \t");
      out.write("\t\t<ul class=\"list-unstyled components mb-5\">\r\n");
      out.write("\t          <li class=\"active\">\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-home\"></span>Accueil</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li>\r\n");
      out.write("\t            <a href=\"#confirurationSubmenu\" data-toggle=\"collapse\" aria-expanded=\"false\" class=\"dropdown-toggle\"><span class=\"fa fa-cog\"></span>Configuration</a>\r\n");
      out.write("\t            <ul class=\"collapse list-unstyled\" id=\"confirurationSubmenu\">\r\n");
      out.write("\t            \t<li>\r\n");
      out.write("\t                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/AnneeScolaire\"><i class=\"fa fa-calendar-alt mr-2\"></i>Année scolaire</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/CyclesFilieresNiveaux\"><i class=\"fa fa-sitemap mr-2\"></i>Filières</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/ClassesGeneriques\"><i class=\"fa fa-chalkboard mr-2\"></i>Classes Génériques</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/UnitesMatieresModules\"><i class=\"fa fa-square-root-alt mr-2\"></i>Matières</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/Evaluations\"><i class=\"fa fa-file-signature mr-2\"></i>Evaluations</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("              \t</ul>\r\n");
      out.write("              </li>\r\n");
      out.write("\t          <li> \r\n");
      out.write("\t              <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/Classes\"><span class=\"fa fa-chalkboard-teacher\"></span>Classes</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li> \r\n");
      out.write("\t              <a href=\"#\"><span class=\"far fa-calendar-alt\"></span>Emplois</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-user-tie\"></span>Personnel</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li>\r\n");
      out.write("\t            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/Etudiants\"><span class=\"fa fa-users\"></span>Etudiants</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t          <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-file-signature\"></span>Evaluations</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-user-check\"></span>Absences</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-book\"></span>Bibliothèque</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-desktop\"></span>Materiel</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-bullhorn\"></span>Annonces</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-newspaper\"></span>Actualités</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"far fa-file-alt\"></span>Cahiers du texte</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-project-diagram\"></span>Projets</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-tools\"></span>Stages</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-file-upload\"></span>Documents</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t\t\t  <li>\r\n");
      out.write("\t            <a href=\"#\"><span class=\"fa fa-print\"></span>Photocopie</a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t </ul>");
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t<!-- Page Content  -->\r\n");
      out.write("      <div id=\"content\" class=\"container\">\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\r\n");
      out.write("          <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("            <button type=\"button\" id=\"sidebarCollapse\" class=\"btn btn-primary\">\r\n");
      out.write("              <i class=\"fa fa-bars\"></i>\r\n");
      out.write("              <span class=\"sr-only\">Toggle Menu</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button class=\"btn btn-dark d-inline-block d-lg-none ml-auto\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <i class=\"fa fa-bars\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("              <ul class=\"nav navbar-nav ml-auto\">\r\n");
      out.write("                <li class=\"nav-item active\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\"><span class=\"fa fa-home mr-2\"></span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\"><span class=\"fa fa-envelope mr-2\"></span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"#\"><span class=\"fa fa-bell mr-2\"></span></a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t    <button class=\"btn btn-default dropdown-toggle\" type=\"button\" id=\"menu1\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t     <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Document/Download?file=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userPhoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"rounded-circle\" style=\"width:20px;height:20px;\">\r\n");
      out.write("\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t    </button>\r\n");
      out.write("\t\t\t\t\t    <div class=\"dropdown-menu dropdown-menu-right\" role=\"menu\" >\r\n");
      out.write("\t\t\t\t\t      <div class=\"dropdown-item text-center\">\r\n");
      out.write("\t\t\t\t\t      <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Document/Download?file=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userPhoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" class=\"rounded-circle\" style=\"width:60px;height:60px;\">\r\n");
      out.write("\t\t\t\t\t       \r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t      <h5 class=\"dropdown-header text-primary text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userFirstName_Fr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(" &nbsp; ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userLastName_Fr}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t      <h5 class=\"dropdown-header text-muted text-center\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userRole}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</h5>\r\n");
      out.write("\t\t\t\t\t      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t      <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/E.DirecteurEtudes/Profile?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t      \t\t<span class=\"fa fa-id-card mr-2\"></span>\r\n");
      out.write("\t\t\t\t\t      \t\tProfile\r\n");
      out.write("\t\t\t\t\t      </a>\r\n");
      out.write("\t\t\t\t\t      <div class=\"dropdown-divider\"></div>\r\n");
      out.write("\t\t\t\t\t\t  <a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/Logout\"> \r\n");
      out.write("\t\t\t\t\t\t      \t<span class=\"fa fa-external-link-square-alt mr-2\"></span>\r\n");
      out.write("\t\t\t\t\t\t      \tDéconnexion\r\n");
      out.write("\t\t\t\t\t\t  </a>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("                </li>\r\n");
      out.write("     \r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("<!-- Start content -->\r\n");
      out.write("\t<div class=\"container\"> \r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-9\"> <!-- Col 1 -->\r\n");
      out.write("\t   \t\t<div class=\"alert bg-light text-secondary\" role=\"alert\">\r\n");
      out.write("\t   \t\t\t<span class=\"fa fa-id-card mr-2\"></span>\r\n");
      out.write("\t   \t\t\tProfile\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t</div> <!-- /Col 1 -->\r\n");
      out.write("\t\t<div class=\"col-md-3\"> <!-- Col 2 -->\r\n");
      out.write("\t\t\t<div class=\"panel with-nav-tabs panel-primary\">\r\n");
      out.write("\t\t\t<div class=\"panel\">\r\n");
      out.write("\t\t     <div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<nav class=\"nav nav-tabs flex-column flex-sm-row\"  id=\"Tab-Content-2\" role=\"tablist\">\r\n");
      out.write("\t\t\t\t\t    <a id=\"tab_Annonces\" href=\"#content-tab-Annonces\" class=\"nav-item nav-link active\" data-toggle=\"tab\" role=\"tab\" aria-controls=\"content-tab-Annonces\" aria-selected=\"false\">\r\n");
      out.write("\t\t\t\t\t        <span class=\"fa fa-bullhorn\"></span> Annonces\r\n");
      out.write("\t\t\t\t\t    </a>\r\n");
      out.write("\t\t\t\t\t    <a  id=\"tab_Actualites\" href=\"#content-tab-Actualites\" class=\"nav-item nav-link\" data-toggle=\"tab\" role=\"tab\" aria-controls=\"content-tab-Actualites\" aria-selected=\"false\">\r\n");
      out.write("\t\t\t\t\t        <span class=\"fa fa-newspaper\"></span> Actualites\r\n");
      out.write("\t\t\t\t\t    </a>\r\n");
      out.write("\t\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t    <div class=\"panel-body\">\r\n");
      out.write("\t\t    \t<!-- Début : Tab content  2-->\r\n");
      out.write("\t\t\t\t<div class=\"tab-content\" id=\"Tab-Content-Communication\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Content tab 1 \t: Annonces-->\r\n");
      out.write("\t\t\t\t\t  \t<div id=\"content-tab-Annonces\" class=\"tab-pane active\" role=\"tabpanel\" aria-labelledby=\"content-tab-Annonces\">\r\n");
      out.write("\t\t\t\t\t     <ul>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Annonce 1</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Annonce 2</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Annonce 3</li>\r\n");
      out.write("\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Content tab 1 : Annonces-->\r\n");
      out.write("\t\t\t\t\t\t<!-- Content tab 2 \t: Actualites-->\r\n");
      out.write("\t\t\t\t\t\t<div id=\"content-tab-Actualites\" class=\"tab-pane\" role=\"tabpanel\" aria-labelledby=\"content-tab-Actualites\">\r\n");
      out.write("\t\t\t\t\t\t <ul>\t\r\n");
      out.write("\t\t\t\t\t\t\t<li>Actualité 1</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Actualité 2</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Actualité 3</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Actualite 4</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>Actualité 5</li>\r\n");
      out.write("\t\t\t\t\t\t </ul>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<!-- /Content tab 2\t: Actualites-->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- Fin : Tab content 2 -->\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t</div> <!-- /Col 2 -->\r\n");
      out.write("\t</div><!-- /row 1 -->\r\n");
      out.write("\t<!-- /Page Content  -->\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Modal Success -->\r\n");
      out.write("\t<div id=\"modalSuccess\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t  <div class=\"modal-dialog modal-dialog-centered modal-confirm\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-box bg-success\">\r\n");
      out.write("\t\t\t\t\t<i class=\"material-icons fa fa-check\"></i>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title text-center\">Succès !</h4>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<p class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<!-- On affiche ici le message obtenu du coté serveur -->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-success btn-block\" data-dismiss=\"modal\">Fermer</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- Fin : Moad Success -->\r\n");
      out.write("<!-- Début : Modal error -->\r\n");
      out.write("\t<div id=\"modalError\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t  <div class=\"modal-dialog modal-dialog-centered modal-confirm\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-box bg-danger\">\r\n");
      out.write("\t\t\t\t\t<i class=\"material-icons fa fa-exclamation-triangle\"></i>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title text-center\">Echec !</h4>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<p class=\"text-center\">\r\n");
      out.write("\t\t\t\t\t<!-- On affiche ici le message obtenu du coté serveur -->\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t<button class=\"btn btn-secondary btn-block\" data-dismiss=\"modal\">Fermer</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("<!-- Fin : Moad Error -->\r\n");
      out.write("<!-- Début : Moad Confirmation -->\r\n");
      out.write("<div id=\"modalConfirm\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("\t<div class=\"modal-dialog modal-dialog-centered modal-confirm \" role=\"document\">\r\n");
      out.write("\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t  <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t<div class=\"icon-box bg-warning\">\r\n");
      out.write("\t\t\t\t\t<i class=\"material-icons fa fa-exclamation-triangle\"></i>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t\t<h4 class=\"modal-title text-center\">Supprimer ?</h4>\t\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t<p class=\"text-center\">\r\n");
      out.write("\t\t\t\t\tEtes vous sûre de vouloir supprimer cet enregistrement ?\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t  <div class=\"modal-footer\">\r\n");
      out.write("\t\t    <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-warning  mr-auto\" id=\"delete\">Supprimer</button>\r\n");
      out.write("\t\t    <button type=\"button\" data-dismiss=\"modal\" class=\"btn btn-secondary  \">Annuler</button>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("  \t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Fin : Moad Confirmation-->\r\n");
      out.write("<!-- Début : Moad Loading Ajax -->\r\n");
      out.write("<div id=\"loading-image\" class=\"modal\" tabindex=\"-1\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-centered modal-sm\" >\r\n");
      out.write("        <div class=\"modal-content\" style=\"width: 48px; color:orange;\">\r\n");
      out.write("            <span class=\"fa fa-spinner fa-spin fa-3x\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Fin : Moad Loading Ajax -->\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.min.js\" ></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-ui.min.js\" ></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/popper.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.dataTables.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/dataTables.bootstrap.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/main.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/dataTables.buttons.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/buttons.flash.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jszip.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/pdfmake.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/vfs_fonts.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/buttons.html5.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("\t<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/buttons.print.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  \t<script type=\"text/javascript\">\r\n");
      out.write("  \t\r\n");
      out.write("    </script>\r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
