/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.69
 * Generated at: 2020-05-20 15:43:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstap.min.css\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\t\tbody {\r\n");
      out.write("\t\t\tbackground-color:#fff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/********************************************************************/\r\n");
      out.write("\t\t.panel.with-nav-tabs .panel-heading{\r\n");
      out.write("\t\t    padding: 5px 5px 0 5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel.with-nav-tabs .nav-tabs{\r\n");
      out.write("\t\t\tborder-bottom: none;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.panel.with-nav-tabs .nav-justified{\r\n");
      out.write("\t\t\tmargin-bottom: -1px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/*** PANEL PRIMARY ***/\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li > a,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li > a:focus {\r\n");
      out.write("\t\t    color: #fff;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > .open > a,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > .open > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > .open > a:focus,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li > a:focus {\r\n");
      out.write("\t\t\tcolor: #fff;\r\n");
      out.write("\t\t\tbackground-color: #3071a9;\r\n");
      out.write("\t\t\tborder-color: transparent;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.active > a,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.active > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.active > a:focus {\r\n");
      out.write("\t\t\tcolor: #428bca;\r\n");
      out.write("\t\t\tbackground-color: #fff;\r\n");
      out.write("\t\t\tborder-color: #428bca;\r\n");
      out.write("\t\t\tborder-bottom-color: transparent;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu {\r\n");
      out.write("\t\t    background-color: #428bca;\r\n");
      out.write("\t\t    border-color: #3071a9;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > li > a {\r\n");
      out.write("\t\t    color: #fff;   \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > li > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > li > a:focus {\r\n");
      out.write("\t\t    background-color: #3071a9;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > .active > a,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > .active > a:hover,\r\n");
      out.write("\t\t.with-nav-tabs.panel-primary .nav-tabs > li.dropdown .dropdown-menu > .active > a:focus {\r\n");
      out.write("\t\t    background-color: #4a9fe9;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t/********************************************************************/\r\n");
      out.write("\r\n");
      out.write("\t</style>\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"page-header\">\r\n");
      out.write("\t\t        <h1>Panels with nav tabs.<span class=\"pull-right label label-default\">:)</span></h1>\r\n");
      out.write("\t\t    </div>\r\n");
      out.write("\t\t    <div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t            <div class=\"panel with-nav-tabs panel-primary\">\r\n");
      out.write("\t\t                <div class=\"panel-heading\">\r\n");
      out.write("\t\t                        <ul class=\"nav nav-tabs\">\r\n");
      out.write("\t\t                            <li class=\"active\"><a href=\"#tab1primary\" data-toggle=\"tab\">Primary 1</a></li>\r\n");
      out.write("\t\t                            <li><a href=\"#tab2primary\" data-toggle=\"tab\">Primary 2</a></li>\r\n");
      out.write("\t\t                            <li><a href=\"#tab3primary\" data-toggle=\"tab\">Primary 3</a></li>\r\n");
      out.write("\t\t                            <li class=\"dropdown\">\r\n");
      out.write("\t\t                                <a href=\"#\" data-toggle=\"dropdown\">Dropdown <span class=\"caret\"></span></a>\r\n");
      out.write("\t\t                                <ul class=\"dropdown-menu\" role=\"menu\">\r\n");
      out.write("\t\t                                    <li><a href=\"#tab4primary\" data-toggle=\"tab\">Primary 4</a></li>\r\n");
      out.write("\t\t                                    <li><a href=\"#tab5primary\" data-toggle=\"tab\">Primary 5</a></li>\r\n");
      out.write("\t\t                                </ul>\r\n");
      out.write("\t\t                            </li>\r\n");
      out.write("\t\t                        </ul>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t                <div class=\"panel-body\">\r\n");
      out.write("\t\t                    <div class=\"tab-content\">\r\n");
      out.write("\t\t                        <div class=\"tab-pane in active\" id=\"tab1primary\">Primary 1</div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane \" id=\"tab2primary\">Primary 2</div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane \" id=\"tab3primary\">Primary 3</div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane \" id=\"tab4primary\">Primary 4</div>\r\n");
      out.write("\t\t                        <div class=\"tab-pane \" id=\"tab5primary\">Primary 5</div>\r\n");
      out.write("\t\t                    </div>\r\n");
      out.write("\t\t                </div>\r\n");
      out.write("\t\t            </div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
